export interface Product {
  id: string
  name: string
  description: string
  price: number
  discount: number
  rating: number
  reviews: number
  images: string[]
  category: string
  size: string
  material: string
  finish: string
  features: string[]
  isNew: boolean
  featured: boolean
  waterResistant: boolean
  slipResistant: boolean
  usage: string
}

export const products: Product[] = [
  {
    id: "floor-tile-1",
    name: "Premium Marble Look Floor Tile",
    description:
      "These elegant floor tiles feature a stunning marble-like appearance with natural veining patterns. Made from high-quality porcelain, they offer the luxurious look of marble with enhanced durability and easier maintenance. Price is per square foot.",
    price: 35,
    discount: 0,
    rating: 4,
    reviews: 28,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "floor",
    size: "2x2",
    material: "Porcelain",
    finish: "Polished",
    features: [
      "Marble-like appearance",
      "Durable porcelain construction",
      "Easy to clean and maintain",
      "Suitable for high-traffic areas",
      "Resistant to stains and scratches",
    ],
    isNew: true,
    featured: true,
    waterResistant: true,
    slipResistant: false,
    usage: "Indoor floors, living rooms, dining areas",
  },
  {
    id: "floor-tile-2",
    name: "Rustic Wood Effect Tile",
    description:
      "Bring the warmth and charm of natural wood to your space with these realistic wood-effect tiles. Made from durable ceramic, they offer the beauty of hardwood with enhanced durability and water resistance. Price is per square foot.",
    price: 35,
    discount: 10,
    rating: 5,
    reviews: 42,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "floor",
    size: "2x4",
    material: "Ceramic",
    finish: "Textured",
    features: [
      "Realistic wood grain appearance",
      "Water and stain resistant",
      "Durable and long-lasting",
      "Easy to maintain",
      "Suitable for underfloor heating",
    ],
    isNew: false,
    featured: true,
    waterResistant: true,
    slipResistant: true,
    usage: "Indoor floors, living areas, bedrooms",
  },
  {
    id: "wall-tile-1",
    name: "Modern Subway Wall Tile",
    description:
      "These classic subway tiles offer a timeless look that complements any interior style. Made from high-quality ceramic, they feature a glossy finish that reflects light beautifully and creates a sense of space. Price is per square foot.",
    price: 35,
    discount: 0,
    rating: 4,
    reviews: 36,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "wall",
    size: "1x2",
    material: "Ceramic",
    finish: "Glossy",
    features: [
      "Classic subway design",
      "Glossy finish reflects light",
      "Easy to clean",
      "Resistant to moisture",
      "Versatile application",
    ],
    isNew: false,
    featured: true,
    waterResistant: true,
    slipResistant: false,
    usage: "Kitchen backsplashes, bathroom walls",
  },
  {
    id: "kitchen-tile-1",
    name: "Decorative Kitchen Backsplash Tile",
    description:
      "Add a touch of elegance to your kitchen with these decorative backsplash tiles. Featuring intricate patterns and designs, they create a stunning focal point that enhances the overall aesthetic of your kitchen. Price is per square foot.",
    price: 35,
    discount: 5,
    rating: 5,
    reviews: 19,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "kitchen",
    size: "1x1",
    material: "Ceramic",
    finish: "Matte",
    features: [
      "Intricate decorative patterns",
      "Stain and heat resistant",
      "Easy to clean",
      "Moisture resistant",
      "Durable and long-lasting",
    ],
    isNew: true,
    featured: true,
    waterResistant: true,
    slipResistant: false,
    usage: "Kitchen backsplashes, accent walls",
  },
  {
    id: "bathroom-tile-1",
    name: "Non-Slip Bathroom Floor Tile",
    description:
      "Ensure safety in wet areas with these non-slip bathroom floor tiles. Designed with a textured surface, they provide excellent grip even when wet, making them ideal for bathrooms and shower areas. Price is per square foot.",
    price: 35,
    discount: 0,
    rating: 5,
    reviews: 31,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "bathroom",
    size: "2x2",
    material: "Porcelain",
    finish: "Textured",
    features: [
      "Non-slip textured surface",
      "Water and moisture resistant",
      "Durable and long-lasting",
      "Easy to clean",
      "Resistant to mold and mildew",
    ],
    isNew: false,
    featured: true,
    waterResistant: true,
    slipResistant: true,
    usage: "Bathroom floors, shower areas",
  },
  {
    id: "washbasin-1",
    name: "Modern Ceramic Washbasin",
    description:
      "This sleek and modern ceramic washbasin combines style and functionality. Its clean lines and minimalist design make it a perfect addition to contemporary bathrooms.",
    price: 3500,
    discount: 10,
    rating: 4,
    reviews: 15,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "washbasin",
    size: "Standard",
    material: "Ceramic",
    finish: "Glossy",
    features: [
      "Modern minimalist design",
      "Durable ceramic construction",
      "Easy to clean",
      "Stain resistant",
      "Standard size fits most countertops",
    ],
    isNew: true,
    featured: false,
    waterResistant: true,
    slipResistant: false,
    usage: "Bathrooms, powder rooms",
  },
  {
    id: "floor-tile-3",
    name: "Large Format Concrete Look Tile",
    description:
      "These large format tiles offer the industrial look of concrete with the practicality of porcelain. Perfect for creating a contemporary, minimalist aesthetic in any space. Price is per square foot.",
    price: 35,
    discount: 0,
    rating: 4,
    reviews: 22,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "floor",
    size: "2x4",
    material: "Porcelain",
    finish: "Matte",
    features: [
      "Industrial concrete appearance",
      "Large format for fewer grout lines",
      "Durable and long-lasting",
      "Stain and scratch resistant",
      "Easy to maintain",
    ],
    isNew: false,
    featured: false,
    waterResistant: true,
    slipResistant: true,
    usage: "Indoor floors, commercial spaces",
  },
  {
    id: "wall-tile-2",
    name: "3D Textured Wall Tile",
    description:
      "Add depth and dimension to your walls with these stunning 3D textured tiles. Their unique patterns create visual interest and can transform any wall into a striking feature. Price is per square foot.",
    price: 35,
    discount: 0,
    rating: 5,
    reviews: 17,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "wall",
    size: "1x2",
    material: "Ceramic",
    finish: "Textured",
    features: [
      "Unique 3D textured patterns",
      "Creates visual interest",
      "Easy to install",
      "Durable and long-lasting",
      "Makes a striking feature wall",
    ],
    isNew: true,
    featured: false,
    waterResistant: true,
    slipResistant: false,
    usage: "Feature walls, living areas, commercial spaces",
  },
  {
    id: "kitchen-tile-2",
    name: "Mosaic Kitchen Tile",
    description:
      "These intricate mosaic tiles add a touch of artistry to any kitchen. Available in a variety of colors and patterns, they're perfect for creating a unique backsplash or accent wall. Price is per square foot.",
    price: 35,
    discount: 5,
    rating: 4,
    reviews: 24,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "kitchen",
    size: "1x1",
    material: "Glass",
    finish: "Glossy",
    features: [
      "Intricate mosaic patterns",
      "Variety of colors available",
      "Heat and stain resistant",
      "Easy to clean",
      "Creates a unique focal point",
    ],
    isNew: false,
    featured: false,
    waterResistant: true,
    slipResistant: false,
    usage: "Kitchen backsplashes, accent walls",
  },
  {
    id: "bathroom-tile-2",
    name: "Marble Effect Bathroom Tile",
    description:
      "Bring luxury to your bathroom with these stunning marble effect tiles. They offer the elegant look of natural marble with the practicality and durability of porcelain. Price is per square foot.",
    price: 35,
    discount: 0,
    rating: 5,
    reviews: 29,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "bathroom",
    size: "2x2",
    material: "Porcelain",
    finish: "Polished",
    features: [
      "Realistic marble veining",
      "Luxurious appearance",
      "Water and stain resistant",
      "Durable and long-lasting",
      "Easy to maintain",
    ],
    isNew: false,
    featured: false,
    waterResistant: true,
    slipResistant: false,
    usage: "Bathroom walls, floors, shower areas",
  },
  {
    id: "washbasin-2",
    name: "Counter Top Washbasin",
    description:
      "This elegant counter top washbasin adds a touch of luxury to any bathroom. Its raised design creates a striking focal point while providing practical functionality.",
    price: 4200,
    discount: 0,
    rating: 4,
    reviews: 13,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "washbasin",
    size: "Standard",
    material: "Ceramic",
    finish: "Glossy",
    features: [
      "Elegant raised design",
      "Premium ceramic construction",
      "Stain resistant",
      "Easy to clean",
      "Creates a luxury bathroom focal point",
    ],
    isNew: false,
    featured: false,
    waterResistant: true,
    slipResistant: false,
    usage: "Bathrooms, luxury spaces",
  },
  {
    id: "floor-tile-4",
    name: "Terrazzo Look Floor Tile",
    description:
      "These terrazzo-inspired tiles bring a playful yet sophisticated look to any space. The speckled design adds visual interest while the durable porcelain construction ensures longevity. Price is per square foot.",
    price: 35,
    discount: 0,
    rating: 4,
    reviews: 18,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: "floor",
    size: "2x2",
    material: "Porcelain",
    finish: "Matte",
    features: [
      "Trendy terrazzo-inspired design",
      "Durable porcelain construction",
      "Stain and scratch resistant",
      "Easy to maintain",
      "Adds visual interest to any space",
    ],
    isNew: true,
    featured: false,
    waterResistant: true,
    slipResistant: true,
    usage: "Indoor floors, commercial spaces",
  },
]
